(() => {
  const $ = id => document.getElementById(id);
  const cfg = window.STOCK_CONFIG || {};
  const cartKey = '3d_peintures_new_cart_v1';
  const clientsKey = '3d_peintures_clients_v1';
  let products = [], cart = JSON.parse(localStorage.getItem(cartKey) || '[]'), selected = null, catalogProducts = [];
  const money = n => Number(n || 0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2});
  const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const available = p => Number(p.total_pieces || 0) > Number(p.minimum_stock || 0);
  function toast(text){$('toast').textContent=text;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2200)}
  function openPanel(id){document.querySelectorAll('.side-panel').forEach(x=>x.classList.remove('open'));$(id).classList.add('open');$('shade').hidden=false}
  function closePanels(){document.querySelectorAll('.side-panel').forEach(x=>x.classList.remove('open'));$('shade').hidden=true}
  function priceFor(p){const old=catalogProducts.find(x=>String(x.code||'').trim().toLowerCase()===String(p.product_code||'').trim().toLowerCase());return Number(old?.price || old?.priceTiers?.[0]?.price || 0)}
  function renderProducts(){const q=String($('status').dataset.query||'').toLowerCase();const list=products.filter(p=>`${p.product_name} ${p.product_code}`.toLowerCase().includes(q));$('productsGrid').innerHTML=list.map(p=>{const ok=available(p),image=p.image_url||'';return `<article class="product-card" data-id="${esc(p.id)}"><div class="product-image"><span class="availability ${ok?'':'off'}">${ok?'متوفر':'غير متوفر حاليا'}</span>${image?`<img src="${esc(image)}" alt="${esc(p.product_name)}">`:'<div class="no-image">3D</div>'}</div><div class="product-info"><div class="product-code">${esc(p.category||'PRODUITS')} · ${esc(p.product_code||'')}</div><h3>${esc(p.product_name)}</h3><div class="product-price">${money(priceFor(p))} <small>درهم / قطعة</small></div><div class="product-meta">${Number(p.pieces_per_box)||0} قطعة في العلبة</div></div></article>`}).join('');$('empty').hidden=!!list.length;$('status').textContent=`${list.length} منتوج`;document.querySelectorAll('.product-card').forEach(card=>card.onclick=()=>openProduct(card.dataset.id))}
  function openProduct(id){selected=products.find(p=>String(p.id)===String(id));if(!selected)return;const ok=available(selected),price=priceFor(selected);$('modalImage').src=selected.image_url||'';$('modalImage').style.display=selected.image_url?'block':'none';$('modalCategory').textContent=selected.category||'PRODUITS';$('modalName').textContent=selected.product_name||'';$('modalCode').textContent=`Code : ${selected.product_code||'—'}`;$('modalStatus').textContent=ok?'متوفر':'غير متوفر حاليا';$('modalStatus').style.color=ok?'#087443':'#b42318';$('modalPrice').textContent=`${money(price)} درهم`;$('modalPerBox').textContent=`${Number(selected.pieces_per_box)||0} قطعة في العلبة`;$('modalBoxes').value=1;$('modalPieces').value=Number(selected.pieces_per_box)||1;updateTotal();$('productModal').hidden=false}
  function updateTotal(){if(!selected)return;const qty=Number($('modalPieces').value)||0;$('modalTotal').textContent=`المجموع: ${money(qty*priceFor(selected))} درهم`}
  function saveCart(){localStorage.setItem(cartKey,JSON.stringify(cart));renderCart()}
  function addSelected(){if(!selected||!available(selected)){toast('المنتوج غير متوفر حاليا');return}const pieces=Math.max(1,Number($('modalPieces').value)||1),row=cart.find(x=>String(x.id)===String(selected.id));if(row)row.pieces+=pieces;else cart.push({id:selected.id,pieces});saveCart();$('productModal').hidden=true;toast('تزاد المنتوج للسلة')}
  function changeCartQuantity(id,delta){const row=cart.find(x=>String(x.id)===String(id));if(!row)return;row.pieces=Math.max(0,Number(row.pieces||0)+delta);cart=cart.filter(x=>x.pieces>0);saveCart()}
  function renderCart(){let total=0;$('cartItems').innerHTML=cart.map(row=>{const p=products.find(x=>String(x.id)===String(row.id));if(!p)return '';const line=Number(row.pieces||0)*priceFor(p);total+=line;return `<div class="cart-row"><img src="${esc(p.image_url||'')}" alt=""><div class="cart-details"><h4>${esc(p.product_name)}</h4><small>${row.pieces} قطعة · ${money(line)} درهم</small></div><div class="cart-quantity"><button class="quantity-btn" data-cart-minus="${esc(row.id)}" type="button">−</button><strong>${row.pieces}</strong><button class="quantity-btn" data-cart-plus="${esc(row.id)}" type="button">+</button></div></div>`}).join('')||'<div class="empty">السلة خاوية.</div>';$('cartTotal').textContent=`${money(total)} درهم`;$('cartBadge').textContent=cart.reduce((s,x)=>s+Number(x.pieces||0),0)}
  function renderCustomers(){let clients=[];try{clients=JSON.parse(localStorage.getItem(clientsKey)||'[]')}catch(e){}const q=String($('customerSearch').value||'').toLowerCase();const list=clients.filter(c=>JSON.stringify(c).toLowerCase().includes(q));$('customersList').innerHTML=list.map(c=>`<div class="customer-row"><b>${esc(c.name||c.client||c.fullName||'زبون')}</b><div>${esc(c.city||'')} ${esc(c.phone||c.tel||'')}</div></div>`).join('')||'<div class="empty">مازال ما تسجل حتى زبون.</div>'}
  function renderOrders(){let orders=[];try{orders=JSON.parse(localStorage.getItem('3d_peintures_orders_v1')||'[]')}catch(e){}$('ordersList').innerHTML=orders.map((order,index)=>`<div class="customer-row"><b>طلبية ${esc(order.orderCode||index+1)}</b><div>${esc(order.client||'بدون زبون')} · ${money(order.total||0)} درهم</div><small>${esc(order.date||order.updatedAt||'')}</small></div>`).join('')||'<div class="empty">مازال ما تسجل حتى طلبية.</div>'}
  async function loadCatalogPrices(){try{const seed=window.CATALOG_SEED;if(seed?.products)catalogProducts=seed.products}catch(e){}}
  async function loadProducts(){if(!window.supabase||!cfg.url||!cfg.anonKey){$('status').textContent='إعدادات المخزون ناقصة';return}const client=window.supabase.createClient(cfg.url,cfg.anonKey);const result=await client.from('stock_products').select('id,product_name,product_code,category,pieces_per_box,total_pieces,minimum_stock,image_url,updated_at').order('product_name');if(result.error){$('status').textContent='تعذر تحميل المنتوجات';toast(result.error.message);return}products=result.data||[];renderProducts();renderCart()}
  $('cartBtn').onclick=()=>{renderCart();openPanel('cartPanel')};$('customersBtn').onclick=()=>{renderCustomers();openPanel('customersPanel')};$('menuBtn').onclick=()=>openPanel('menuPanel');$('menuCustomersBtn').onclick=()=>{closePanels();renderCustomers();openPanel('customersPanel')};$('menuOrdersBtn').onclick=()=>{closePanels();renderOrders();openPanel('ordersPanel')};$('editProductsBtn').onclick=()=>{location.href='stock.html#products'};$('shade').onclick=closePanels;$('clearCart').onclick=()=>{cart=[];saveCart()};$('saveOrder').onclick=()=>toast(cart.length?'تحفظات الطلبية فهاد الجهاز':'السلة خاوية');$('refreshBtn').onclick=()=>loadProducts();$('customerSearch').oninput=renderCustomers;$('addCustomer').onclick=()=>toast('إضافة الزبون كتحتاج خانة البيانات');$('addToCart').onclick=addSelected;$('modalBoxes').oninput=()=>{$('modalPieces').value=(Number($('modalBoxes').value)||0)*(Number(selected?.pieces_per_box)||1);updateTotal()};$('modalPieces').oninput=updateTotal;document.querySelectorAll('[data-close]').forEach(btn=>btn.onclick=()=>{const id=btn.dataset.close;if(id==='productModal')$(id).hidden=true;else closePanels()});document.addEventListener('click',event=>{const plus=event.target.closest('[data-cart-plus]'),minus=event.target.closest('[data-cart-minus]');if(plus)changeCartQuantity(plus.dataset.cartPlus,1);if(minus)changeCartQuantity(minus.dataset.cartMinus,-1)});
  loadCatalogPrices().then(loadProducts);setInterval(loadProducts,30000);
})();
