(()=>{
const $=id=>document.getElementById(id),cfg=window.STOCK_CONFIG||{},rawScope=sessionStorage.getItem('commercialUserName')||sessionStorage.getItem('commercialUserId')||'guest',scope=String(rawScope).replace(/[^a-zA-Z0-9_-]/g,'_'),keyStore=`3d_peintures_commercial_prices_v1__${scope}`;let products=[];
const money=n=>Number(n||0).toLocaleString('fr-FR',{minimumFractionDigits:2,maximumFractionDigits:2}),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
function getPrices(){try{return JSON.parse(localStorage.getItem(keyStore)||'{}')}catch(e){return {}}}
function render(){const all=getPrices();$('pricesList').innerHTML=products.map(p=>{const code=String(p.product_code||'').trim().toLowerCase(),v=all[code]||{};return `<article class="price-card"><div class="price-card-head"><h3>${esc(p.product_name||'بدون اسم')}</h3><small>${esc(p.product_code||'بدون كود')} · ${Number(p.pieces_per_box)||0} قطعة/علبة</small></div><div class="price-fields"><label>الثمن العادي<input data-price="${esc(p.id)}" type="number" min="0" step="0.01" value="${Number(v.price??0)||0}"></label><label>شري عدد<input data-buy="${esc(p.id)}" type="number" min="0" step="1" placeholder="مثال 10" value="${Number(v.offerBuy)||0}"></label><label>وخد مجاناً<input data-free="${esc(p.id)}" type="number" min="0" step="1" placeholder="مثال 1" value="${Number(v.offerFree)||0}"></label><label>عدد العلب للعرض<input data-boxes="${esc(p.id)}" type="number" min="0" step="1" placeholder="مثال 5" value="${Number(v.offerBoxes)||0}"></label><label>قيمة التخفيض<input data-discount="${esc(p.id)}" type="number" min="0" step="0.01" placeholder="درهم" value="${Number(v.discount)||0}"></label><button class="save-one" data-save="${esc(p.id)}" type="button">حفظ</button></div></article>`}).join('')||'<div class="empty">مازال ما كاين حتى منتوج فالمخزن.</div>';$('pricesStatus').textContent=`${products.length} منتوج محمل من المخزن`}
function save(id,button){const p=products.find(x=>String(x.id)===String(id));if(!p)return;const code=String(p.product_code||'').trim().toLowerCase(),all=getPrices(),old=all[code]||{};all[code]={...old,price:Number(document.querySelector(`[data-price="${CSS.escape(String(id))}"]`).value)||0,offerBuy:Number(document.querySelector(`[data-buy="${CSS.escape(String(id))}"]`).value)||0,offerFree:Number(document.querySelector(`[data-free="${CSS.escape(String(id))}"]`).value)||0,offerBoxes:Number(document.querySelector(`[data-boxes="${CSS.escape(String(id))}"]`).value)||0,discount:Number(document.querySelector(`[data-discount="${CSS.escape(String(id))}"]`).value)||0,updatedAt:new Date().toISOString()};localStorage.setItem(keyStore,JSON.stringify(all));button.textContent='تحفظ';button.classList.add('saved');setTimeout(()=>{button.textContent='حفظ';button.classList.remove('saved')},1200)}
async function load(){if(!window.supabase||!cfg.url||!cfg.anonKey){$('pricesStatus').textContent='إعدادات المخزن ناقصة';return}const client=window.supabase.createClient(cfg.url,cfg.anonKey);let all=[],from=0;while(true){const r=await client.from('stock_products').select('id,product_name,product_code,pieces_per_box').order('product_name').range(from,from+999);if(r.error){$('pricesStatus').textContent='تعذر تحميل منتجات المخزن: '+r.error.message;return}all=all.concat(r.data||[]);if(!r.data||r.data.length<1000)break;from+=1000}products=all;render()}
document.addEventListener('click',e=>{const b=e.target.closest('[data-save]');if(b)save(b.dataset.save,b)});load();
})();
